remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

title: "Pharmacometrics × AI"
description: "Exploring the intersection of pharmacometrics and LLM-based automation"
url: "https://AriAnthony.github.io"

# Navigation
main:
  - title: "Home"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "About"
    url: /about/

# Layout settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      show_date: true
      read_time: true

author:
  name: "Ari Pritchard-Bell"
  bio: "Pharmacometrician exploring AI automation"

markdown: kramdown
highlighter: rouge

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-F6FCRGMJ3Z"
    anonymize_ip: false
